apiVersion: apps/v1 # kubernetes resource 의 API Version
kind: Deployment # kubernetes resource name
metadata: # 메타데이터 : name, namespace, labels, annotations 등을 포함
  name: front-deployment
  labels:
    app: front
spec: # 메인 파트 : resource 의 desired state 를 명시
  replicas: 2 # 동일한 template 의 pod 을 2 개 복제본으로 생성합니다.
  selector:
    matchLabels:
      app: front
  template: # Pod 의 template 을 의미합니다.
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front # container 의 이름
        image: cityjd/front-kuber:v1.0.0 # container 의 image
        ports:
        - containerPort: 8282 # container 의 내부 Port