apiVersion: v1
kind: Service
metadata:
  name: my-fast
  labels:
    run: my-fast
spec:
  ports:
  - port: 8383
    protocol: TCP
    targetPort: 80
  selector: # 아래 label 을 가진 Pod 을 매핑하는 부분입니다.
    app: fast 